FROM golang:1.26-bookworm AS builder
WORKDIR /src
COPY go.mod go.sum* ./
RUN go mod download
COPY . ./
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/stund ./cmd/stund

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /out/stund /app/stund
EXPOSE 3708/udp
ENTRYPOINT ["/app/stund"]
